### ISSUE TITLE
Unable to make feathers-pinia-quasar to work. The requested module does not provide an export named 'createClient'

### ISSUE THREAD

**Issue by HarisHashim** [rabalyn/feathers-pinia-quasar#13]
Hello, I am getting this error in a test project using Quasar CLI and Vite. I did another test project using webpack and that works using same code etc.

```
[Quasar] boot error: SyntaxError: The requested module '/@fs/D:/Project/Feathers/back-end/lib/client.js' does not provide an export named 'createClient' (at feathers-client.ts:1:10)

SyntaxError: The requested module '/@fs/D:/Project/Feathers/back-end/lib/client.js' does not provide an export named 'createClient' (at feathers-client.ts:1:10)
```

back-end lib is actually a Feathers JS project where I use `npm link` to link it to Quasar project where I did `npm link back-end` in Quasar project folder to complete the link.

```
// feathers-client.ts

import { createClient } from 'back-end';
import { createPiniaClient } from 'feathers-pinia';
import socketio from '@feathersjs/socketio-client';
import io from 'socket.io-client';

// import { feathers } from '@feathersjs/feathers';
import { pinia } from './modules/pinia';

const host = 'http://localhost:3030';
const socket = io(host, { transports: ['websocket'] });

// const app = feathers();

export const feathersClient = createClient(socketio(socket), {
  storage: window.localStorage,
});

// export const feathersClient = app.configure(socketio(socket));

export const api = createPiniaClient(feathersClient, {
  pinia,
  idField: 'id',
  whitelist: ['$regex'],
  paramsForServer: [],
});
```

**Comment by HarisHashim** [comment]
I thought that adding vite config in quasar.config will fix the problem.

Infact, initially the Quasar project will not even build until I add the following config

```
//quasar.config.js

const { mergeConfig } = require('vite');   // <== beginning of file

// in   build: {}
extendViteConf(viteConf) {
  viteConf.build = mergeConfig(viteConf.build, {
    rollupOptions: {
      external: ['back-end'],
    },
  });
},

```

Adding this line result to a successful quasar build. But during runtime and in browser console. Errors as in first post is seen.

Appreciate help and thanks in advance!

**Comment by HarisHashim** [comment]
Update! Managed to make things work. In short `npm link` doesn't work. Need to use `npm pack`.

I  create a repo [qfp-starter](https://github.com/HarisHashim/qfp-starter) . Please have a go at the readme file and take a look at package.json scripts section.

Hope this help other people trying to make feathers-pinia-quasar to work!

**Comment by rabalyn** [comment]
Hey there and thanks for reaching out!

I went over this example project and updated the setup instructions and upgraded the used dependencies.
I went for the approach of installing the bundled client as a [dependency](https://github.com/rabalyn/feathers-pinia-quasar/blob/main/package.json#L18) in the project. I am currently too busy to wrap my head around the npm link / packing stuff that I never used before^^"
You can take a look at [this new section](https://github.com/rabalyn/feathers-pinia-quasar?tab=readme-ov-file#feathers-chat---prerequisite-backend) in the readme.

I added a link to your repository for the `npm link/pack` setup - thanks for setting that up!

**Comment by rabalyn** [comment]
> I thought that adding vite config in quasar.config will fix the problem.
> 
> Infact, initially the Quasar project will not even build until I add the following config
> 
> ```
> //quasar.config.js
> 
> const { mergeConfig } = require('vite');   // <== beginning of file
> 
> // in   build: {}
> extendViteConf(viteConf) {
>   viteConf.build = mergeConfig(viteConf.build, {
>     rollupOptions: {
>       external: ['back-end'],
>     },
>   });
> },
> ```
> 
> Adding this line result to a successful quasar build. But during runtime and in browser console. Errors as in first post is seen.
> 
> Appreciate help and thanks in advance!

I didn't touch the quasar.config during my upgrade - so I am actually not sure if this is really needed?
But I am not confident in this regard, because my dev setup changed since I initially setup this repository.

What was the building error for you? Was it eslint-related?

**Comment by HarisHashim** [comment]
Looking at recent changes to feathers-pinia-quasar main branch. In package.json file:

```  
    "dependencies": {
    "@feathersjs/authentication-client": "^5.0.31",
    "@feathersjs/feathers": "^5.0.31",
    "@feathersjs/socketio-client": "^5.0.31",
    "@quasar/extras": "^1.16.13",
    "@vueuse/core": "^12.0.0",
    "feathers-chat": "http://localhost:3030/feathers-chat-0.0.0.tgz",
```

The last line in above, added feathers-chat as dependency. This was not there in previous release. And should solve the problem I encountered earlier.

I look further into feathers-chat code in [package.json]( https://github.com/feathersjs/feathers-chat/blob/dove/feathers-chat-ts/package.json). The command bundle:client script

```
    "bundle:client": "npm run compile && npm pack --pack-destination ../public",
```

So the way I understand this, it should work since running feathers-chat will host feathers-chat-0.0.0.tgz and make it available as dependency to feathers-pinia-quasar through http://localhost:3030/feathers-chat-0.0.0.tgz . 

Maybe someone else can test this. My development environment have changed too since I fix things in my repo (qfp-quasar) and upgrade everything to node version 20.

I tried anyway and get this error when doing npm install for feathers-pinia-quasar

```
npm WARN deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated gauge@4.0.4: This package is no longer supported.
npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
```

```
npm ERR! code EINTEGRITY
npm ERR! sha512-EOPui2GVullNyA01bH2lDf+yZOaE83SPtGPGTlMEsSIwXnGfsc9RbhPavoYRB4ro80QlY7SnQTiYkjjmRqBrBw== integrity checksum failed when using sha512: wanted sha512-EOPui2GVullNyA01bH2lDf+yZOaE83SPtGPGTlMEsSIwXnGfsc9RbhPavoYRB4ro80QlY7SnQTiYkjjmRqBrBw== but got sha512-dX1zFao5JY2VP1DvWkZDwAO5MVMe8AuuUNxILaS9hKa4NO2hVQGMQGAH+5HIe3QQ76Ox0Ol6FlpwtTbpgRZwnQ==. (5967 bytes)
```

I believe that we can close this issue. Taking note that, perhaps the repo itself need to be updated to latest Node, Feathers and Quasar.
